### ISSUE TITLE
Unable to change Mental status of Talas as Game Master, unable to influence Talas as player

### ISSUE THREAD

**Issue by fauxtail** [xavier150/MMVS#16]
When in game master mode the "Mental" heading shows but the slider options for "Angry" and "Tired" (as showcased in the Nov 2021 devblog) are absent.

Additionally, when playing I have been unable to adjust these values through gameplay.  There does not seem to be any way to influence these values such as through running away, or if there is then time spent cleaning is too hard to work off to enable angry behaviors such as stomps

**Comment by xavier150** [comment]
Hello @fauxtail 
Thank for the report! Since the HotFix v0.4.0.1 Talas AI work a lot better. You can make him angry when you make him sit on floor them you go away without rub his talons. After a delay he will try to stomp you or vore you.

About the options "Angry", "Tired" and the other actions. That for have more control on want Talas want to do. I hidden some sliders I will add it again when AI will work as I want. :3

I keep this issue open.

**Comment by xavier150** [comment]
Hello! Since I fully replace with the decision table. I will close this issue.
Thanks again gor the report!
