### ISSUE TITLE
-NOHMD launch parameter still launches SteamVR (Windows)

### ISSUE THREAD

**Issue by sabertooth604** [xavier150/MMVS#31]
SteamVR launches even though the -nohmd launch option has been given.

**Comment by xavier150** [comment]
-nohmd don't have impact on Steam VR. -nohmd is for launch the game as desktop mode and this is done by default.
Steam VR launche by default when the game start because I use the plugin Steam VR. I will switch to Open XR for v0.5.0
https://forums.unrealengine.com/t/how-to-disable-auto-steamvr-launch-on-ue4-launch/361874

**Comment by xavier150** [comment]
Hello, thanks again for the report! 
Since the game switch from Open VR (Steam VR) to Open XR. 
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.2_Alpha.md

So I will close this issue.
